# sample netlify.toml
[build]
  command = "npm run build"
  functions = "./functions"
  publish = "build"

# note: each of these fields are OPTIONAL
[dev]
  command = "npm run dev"
  port = 8080
  autoLaunch = true